# docker-compose -f docker-compose.dev.yml
version: "3.7"

services:

  db:
    image: mariadb:10.5
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'p@ssw0rd'
      MYSQL_DATABASE: "troll_bot"
      MYSQL_USER: "troll_bot"
      MYSQL_PASSWORD: "troll_bot_p@ssw0rd"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - db

volumes:
  mariadb-data: