# docker-compose -f docker-compose.prod.yml up -d

version: "3.7"

services:
  db:
    image: mariadb:10.5
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file: environments/bot.env
    networks:
      - back-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    env_file: environments/bot.env
    depends_on:
      - db
    networks:
      - back-network

  bot:
    image: discord-bot
    build: .
    env_file: environments/bot.env
    volumes:
      - ${PWD}/troll-bot-config.yml:/app/troll-bot-config.yml
    depends_on:
      - db
    networks:
      - back-network

volumes:
  mariadb-data:

networks:
  back-network:
    driver: bridge